### ISSUE TITLE
varnish

### ISSUE THREAD

**Issue by laurentdebricon** [moviepilot/seoserver#3]
You say "Your webserver has to detect incoming search engine requests in order to route them to the seoserver. A quite lazy way in doing so is looking for the string "bot" in the User-Agent-Header. "

I think it's against google policies to do that, you're not showing the same content based on useragent.

I think a bette solution is just : 

backend nodejs{
    .host = "127.0.0.1";
    .port = "1337";
}

backend seoserver {
    .host = "127.0.0.1";
    .port = "10300";
}

sub vcl_recv {

   if (req.url ~ "escaped_fragment") {
     set req.backend = seoserver;
    } else {
     set req.backend = nodejs;
    }

 return (lookup);

}

Anyway no offence i put it here for everybody :)

**Comment by nuc** [comment]
Hey,

Thanks for noticing it. I updated the readme accordingly.
