### ISSUE TITLE
seoserver.js start not working

### ISSUE THREAD

**Issue by anil1712** [moviepilot/seoserver#4]
Hi, I have done with all required dependencies, but it still not working any more. I am using W8-64bit and testing locally in my system, you can see my folder structure in the attached snap. While `bin/seoserver start -p 10300` or `node lib/seoserver.js start` its throwing below exception.

```
    module.js:340
    throw err;
          ^
    Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (f:\user\javascript\bot\seoserver\lib\
seoserver.js:6:13)
    at Object.<anonymous> (f:\user\javascript\bot\seoserver\lib\
seoserver.js:311:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

![folder-str](https://cloud.githubusercontent.com/assets/4207865/2728392/2581824e-c5f1-11e3-9f96-d5a8cac40037.png)

**Comment by nuc** [comment]
Hey there,

It seems that express was not installed. 

Can you try `npm install` again and check the log for any errors?

**Comment by anil1712** [comment]
After `npm install` it downloads the express but still getting some exceptions

```
C:\Users\AppData\Roaming\npm\node_modules\seoserver\bin SeoServer succes
sfully started

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1127:5)
    at Function.app.listen (C:\Users\AppData\Roaming\npm\node_modules\se
oserver\node_modules\express\lib\application.js:532:24)
    at Object.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\seo
server\lib\seoserver.js:56:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by adelgado** [comment]
On Thu, Apr 17, 2014 at 11:54 AM, Anil Kumar Pandey <
notifications@github.com> wrote:

> After npm install it downloads the express but still getting some
> exceptions
> 
> C:\Users\AppData\Roaming\npm\node_modules\seoserver\bin SeoServer succes
> sfully started
> 
> events.js:72
>         throw er; // Unhandled 'error' event
>               ^
> Error: listen EADDRINUSE
>     at errnoException (net.js:901:11)
>     at Server._listen2 (net.js:1039:14)
>     at listen (net.js:1061:10)
>     at Server.listen (net.js:1127:5)
>     at Function.app.listen (C:\Users\AppData\Roaming\npm\node_modules\se
> oserver\node_modules\express\lib\application.js:532:24)
>     at Object.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\seo
> server\lib\seoserver.js:56:5)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
> 
> Hello Anil,

You seem to already have an application bound to the port you are trying to
bind the seoserver to. Maybe try a different port, or check if you can stop
whatever process is bound to that port?

Cheers,

--ad

**Comment by anil1712** [comment]
I tried with different port but not getting any response in browser chrome says `could not connect to localhost:10300`

```
F:\javascript\bot\seoserver_moviepilot>seoserver start
-p 10300
C:\Users\AppData\Roaming\npm\node_modules\seoserver\bin SeoServer succes
sfully started
```

**Comment by kdesineedi** [comment]
Hi all,

For the benefit of "new-to-node.js" people like me:

There is one important step which I figured it out is that this zip has a coffeescript attached to it.

Please install coffeescript (https://github.com/jashkenas/coffeescript).

Compile the config.coffee file which will generate a config.js file.

Copy and paste this config.js file in the lib folder where the seoserver.js file is located.

Then use the node lib/seoserver.js start.

Saludos
  ~K

**Comment by lextoumbourou** [comment]
Thanks, @kdesineedi ! I've updated the README to explain that in [this](https://github.com/moviepilot/seoserver/pull/5) PR.
